# GitHub CI build pipeline
name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests and generate coverage report
        run: |
          cd src
          python -m unittest -v
          coverage run -m unittest
          coverage report
          coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: src/htmlcov

      - name: Run package creation
        run: |
          cd src
          python -m pip install --user --upgrade build
          python -m build

      - name: Archive package
        uses: actions/upload-artifact@v3
        with:
          name: awesome-calculator
          path: src/dist

  install-package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Note: The `install-package` job is only present in the uploaded file, not in the pasted one.
        # This job ensures the package is installed after it is built.

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: awesome-calculator
          # Note: The `download-artifact` step is also unique to the uploaded file.

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install src/dist/dedreira_awesomecalculator-1.0.0-py3-none-any.whl
        # This `install-package` step is not in the pasted file but is essential for package testing.
